name = "Community Crafters"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "625b8df96f7e4ca832a53e666849a3d0c786a525df0673ddb6f6d3e2b84f4469"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[options]
datapack-folder = "datapacks"
