name = "Community Crafters"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd66ea6439767dc4bf1bb0c34581b27660f798d908116f03e1b5b781d101a621"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
