name = "Community Crafters"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bff5f3b868acb2de3d6cb1ca6f6151e16dec79c6f1fa55a67a318a28907144a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[options]
datapack-folder = "datapacks"
